language: android

android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra

before_install:
    - chmod +x ./run-build.sh
    - chmod +x ./gradlew

after_success:
    - git config --global user.email "sumimaito@hotmail.com"
    - git config --global user.name "SumiMakito"
    - export GITHUB_TAG=Snapshot_${TRAVIS_BRANCH}_Build.${TRAVIS_BUILD_NUMBER}
    - git tag ${GITHUB_TAG}
    - git push --quiet https://${GITHUB_KEY}@github.com/SumiMakito/QuickKV.git ${GITHUB_TAG}

deploy:
    provider: releases
    api_key:
      secure: UK/XOuxfPNu/WQWncPUHE53vGp1Bp0OwQgpt14ym2rED/enAunLuwfwmBnhVizvbslI/WGAcQkdQRl+S4TC5MvAdRHNma69e32KvmL2+VFZWf9ZviR5oalYEa4T/4jx1e9XsP0bvuNWZZRGN2vEoBDjZ224jEPzoauuZVSLZusw=
    file:
      - ./library/build/libs/QuickKV_${GITHUB_TAG}.jar
    skip_cleanup: true
    on:
      repo: SumiMakito/QuickKV
      tags: false

branches:
    except: /^(Snapshot).*$/

script:
    ./run-build.sh
