language: android

android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra
    
before_install:
    - chmod +x build.sh
    - chmod +x gradlew

script:
    ./travis-ci/run-build.sh
  