language: android

android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra

before_install:
    - chmod +x ./run-build.sh
    - chmod +x ./gradlew

after_success:
    - git config --global user.email "sumimaito@hotmail.com" > /dev/null
    - git config --global user.name "SumiMakito" > /dev/null
    - export GITHUB_TAG=Snapshot_${TRAVIS_BRANCH}_Build.${TRAVIS_BUILD_NUMBER} > /dev/null
    - git tag ${GITHUB_TAG} > /dev/null
    - git push --quiet https://${GITHUB_KEY}@github.com/SumiMakito/QuickKV.git ${GITHUB_TAG} > /dev/null

deploy:
    provider: releases
    api_key:
      secure: DDy78+mQPnOXz7J0nbxcnSkCIw3sTgcZvZZ7BziOcoN4dJk9Hn+B1OC5NkTR2OW6s1AGtv90glbq+gEp/PRa6RQjva0RRSOneDLeKii7uzgCNkfCI/ErhgL33nlGZB2MYXvLDi5EgSS673zgzUiyO9b4KUojbDP/OSK7idI+Hms=
    file:
      - ./library/build/libs/QuickKV_${GITHUB_TAG}.jar
    skip_cleanup: true
    on:
      repo: SumiMakito/QuickKV
      tags: false

branches:
    except: /^(Snapshot).*$/

script:
    ./run-build.sh > /dev/null
